import pymongo

class MongoConnector:
    def __init__(self, config):
        """Add the database configuration parameters to the object.

        This class expects a single dictionary argument which needs to assign the
        appropriate values to (at least) the following keys:

            host - the IP address of the host running mongodb.
            port - the port used by the mongodb.
            user - the mongodb username to use.
            password - the user's password.
            database - the name of the database to use.

        For more options, refer to the mysql-connector-python documentation.
        """
        self.config = config

    def __enter__(self):
        """Connect to database and create a DB cursor.

        Return the database cursor to the context manager.
        """
        self.client = pymongo.MongoClient()
        return self.client[self.config['database']]

    def __exit__(self, exc_type, exc_value, exc_traceback):
        """Destroy the cursor as well as the connection (after committing).

        Ignore any exceptions generated by the context managed code (for now).
        """
        self.client.close()

def to_list(data):
    items = []
    for item in data:
        items.append(item)
    return items
